const ACTIONS = {
  JOIN: "JOIN",
  LEAVE: "LEAVE",
  ADD_PEER: "ADD_PEER",
  RELAY_ICE: "RELAY_ICE",
  RELAY_SDP: "RELAY_SDP",
  SESSION_DESCRIPTION: "SESSION_DESCRIPTION",
  ICE_CANDIDATE: "ICE_CANDIDATE",
  REMOVE_PEER: "REMOVE_PEER",
  MUTE: "MUTE",
  UNMUTE: "UNMUTE",
};

module.exports = ACTIONS;
